version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "go"
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "uv"
    directory: "test"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
