api_key: $API_KEY
api_url: "$API_URL"
update_frequency: 10s
waf_config:
  - web_acl_name: mywebacl
    fallback_action: ban
    rule_group_name: crowdsec-rule-group-eu-west-1
    scope: REGIONAL
    region: eu-west-1
    ipset_prefix: crowdsec-blocklist-a
  - web_acl_name: test-cloudfront
    fallback_action: captcha
    rule_group_name: crowdsec-rule-group-cloudfront
    scope: CLOUDFRONT
    ipset_prefix: crowdsec-blocklist-cf
